package com.prototype.api.controller.dto;

import lombok.Data;

@Data
public class DanfeDTO {

    private String logo;
    private String enderDest;
    private String naturezaOperacao;
    private String formaPagamento;
    private String serie;
    private String numeroNF;
    private String dataEmissao;
    private String dataSaida;
    private String tipoNF;
    private String ambiente;
    private String emissao;
    private String chave;
    private String protocolo;
    private String versao;
    private String emitenteCnpj;
    private String emitenteNome;
    private String emitenteFantasia;
    private String emitenteIe;
    private String emitenteIest;
    private String emitenteIm;
    private String emitenteLogradouro;
    private String emitenteNumero;
    private String emitenteBairro;
    private String emitenteMunicipio;
    private String emitenteUf;
    private String emitenteCep;
    private String emitenteTelefone;

    private String destinatarioCnpj;
    private String destinatarioCpf;
    private String destinatarioNome;
    private String destinatarioIe;
    private String destinatarioLogradouro;
    private String destinatarioNumero;
    private String destinatarioComplemento;
    private String destinatarioBairro;
    private String destinatarioMunicipio;
    private String destinatarioUf;
    private String destinatarioCep;
    private String destinatarioTelefone;
    private String valorBase;
    private String valorIcms;
    private String valorBaseSt;
    private String valorSt;
    private String valorProdutos;
    private String valorFrete;
    private String valorSeguro;
    private String valorDesconto;
    private String valorOutro;
    private String valorIpi;
    private String valorNf;
    private String frete;
    private String transporteCnpj;
    private String transporteNome;
    private String transporteIe;
    private String transporteEndereco;
    private String transporteMunicipio;
    private String transporteUf;
    private String transporteVolume;
    private String transporteEspecie;
    private String transporteMarca;
    private String transporteNumeracao;
    private String transportePesoB;
    private String transportePesoL;
    private String transporteAntt;
    private String transportePlaca;
    private String transportePlacaUf;
    private String issqnTotal;
    private String issqnBase;
    private String issqnValor;
    private String informacoes;
    private String prodCodigo;
    private String prodDescricao;
    private String prodNcm;
    private String prodCfqp;
    private String prodUnidade;
    private String prodQuantidade;
    private String prodValor;
    private String prodTotal;
    private String prodCson;
    private String prodCts;
    private String prodBc;
    private String prodAliqIcms;
    private String prodValorIcms;
    private String prodAliqIpi;
    private String prodValorIpi;
}
